### ISSUE TITLE
Issue with ARM options @multitable

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/texi2rst#14]
GCC's invoke.texi has:

```
The table below summarizes the permissible values for @var{arch}
and the features that they enable by default:

@multitable @columnfractions 0.20 0.20 0.60
@headitem @var{arch} value @tab Architecture @tab Includes by default
@item @samp{armv8-a} @tab Armv8-A @tab @samp{+fp}, @samp{+simd}
@item @samp{armv8.1-a} @tab Armv8.1-A @tab @samp{armv8-a}, @samp{+crc}, @samp{+lse}, @samp{+rdma}
@item @samp{armv8.2-a} @tab Armv8.2-A @tab @samp{armv8.1-a}
@item @samp{armv8.3-a} @tab Armv8.3-A @tab @samp{armv8.2-a}, @samp{+pauth}
@item @samp{armv8.4-a} @tab Armv8.4-A @tab @samp{armv8.3-a}, @samp{+flagm}, @samp{+fp16fml}, @samp{+dotprod}
@item @samp{armv8.5-a} @tab Armv8.5-A @tab @samp{armv8.4-a}, @samp{+sb}, @samp{+ssbs}, @samp{+predres}
@item @samp{armv8.6-a} @tab Armv8.6-A @tab @samp{armv8.5-a}, @samp{+bf16}, @samp{+i8mm}
@item @samp{armv8-r} @tab Armv8-R @tab @samp{armv8-r}
@end multitable
```
which was added in this gcc commit:

 ```
commit a93e1d5c70abe9fba3522318131a352fad0a4f48
Author: Dennis Zhang <dennis.zhang@arm.com>
Date:   Fri Dec 13 10:22:39 2019 +0000

    [AArch64] Enable CLI for Armv8.6-a: armv8.6-a, i8mm and bf16
    
    2019-12-13  Dennis Zhang  <dennis.zhang@arm.com>
    
    gcc/
            * config/aarch64/aarch64-arches.def (armv8.6-a): New.
            * config/aarch64/aarch64-c.c (aarch64_update_cpp_builtins): Define
            __ARM_FEATURE_MATMUL_INT8, __ARM_FEATURE_BF16_VECTOR_ARITHMETIC and
            __ARM_FEATURE_BF16_SCALAR_ARITHMETIC when enabled.
            * config/aarch64/aarch64-option-extensions.def (i8mm, bf16): New.
            (fp): Disabling fp also disables i8mm and bf16.
            (simd): Disabling simd also disables i8mm.
            * config/aarch64/aarch64.h (AARCH64_FL_V8_6): New macro.
            (AARCH64_FL_I8MM, AARCH64_FL_BF16, AARCH64_FL_FOR_ARCH8_6): Likewise.
            (AARCH64_ISA_V8_6, AARCH64_ISA_I8MM, AARCH64_ISA_BF16): Likewise.
            (TARGET_I8MM, TARGET_BF16_FP, TARGET_BF16_SIMD): Likewise.
            * doc/invoke.texi (armv8.6-a, i8mm, bf16): Document new options
            and add a new table to list permissible values for ARCH.
    
    gcc/testsuite/
            * gcc.target/aarch64/pragma_cpp_predefs_2.c: Add tests for i8mm
            and bf16 features.
    
    From-SVN: r279370
```

Currently this becomes this XML:

```
<para>The table below summarizes the permissible values for <var>arch</var>
and the features that they enable by default:
</para>
<multitable></multitable><para> <columnfractions></columnfractions> 0.20 0.20 0.60
<headitem></headitem> <var>arch</var> value <tab></tab> Architecture <tab></tab> Includes by default
```

in which the `multitable` and `columnfractions` elements are empty, and most of the content has been dropped.

texi2rst.py fails with an exception on this:

```
Traceback (most recent call last):
  File "./texi2rst.py", line 2693, in <module>
    w.visit(tree)
  File "/home/david/coding-3/texi2rst/node.py", line 196, in visit
    self.visit(child)
  File "/home/david/coding-3/texi2rst/node.py", line 196, in visit
    self.visit(child)
  File "/home/david/coding-3/texi2rst/node.py", line 196, in visit
    self.visit(child)
  [Previous line repeated 3 more times]
  File "/home/david/coding-3/texi2rst/node.py", line 192, in visit
    early_exit = self.previsit_element(node)
  File "./texi2rst.py", line 1411, in previsit_element
    return element.rst_kind.before(self)
  File "./texi2rst.py", line 1360, in before
    table_layout = TableLayout(self.element, self.ctxt.debug)
  File "./texi2rst.py", line 1211, in __init__
    self.num_columns = len(self.components[0].rows[0].entries)
IndexError: list index out of range
```
Clearly we need to do a better job on this table.

**Comment by davidmalcolm** [comment]
Generated HTML for this from the regular texinfo toolchain can be seen at:
  https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#index-march

**Comment by davidmalcolm** [comment]
Seems to work now; the generated .rst is:

```
The table below summarizes the permissible values for :samp:`{arch}`
and the features that they enable by default:

====================  ============  =====================================================================
:samp:`{arch}` value  Architecture  Includes by default
====================  ============  =====================================================================
:samp:`armv8-a`       Armv8-A       :samp:`+fp`, :samp:`+simd`
:samp:`armv8.1-a`     Armv8.1-A     :samp:`armv8-a`, :samp:`+crc`, :samp:`+lse`, :samp:`+rdma`
:samp:`armv8.2-a`     Armv8.2-A     :samp:`armv8.1-a`
:samp:`armv8.3-a`     Armv8.3-A     :samp:`armv8.2-a`, :samp:`+pauth`
:samp:`armv8.4-a`     Armv8.4-A     :samp:`armv8.3-a`, :samp:`+flagm`, :samp:`+fp16fml`, :samp:`+dotprod`
:samp:`armv8.5-a`     Armv8.5-A     :samp:`armv8.4-a`, :samp:`+sb`, :samp:`+ssbs`, :samp:`+predres`
:samp:`armv8.6-a`     Armv8.6-A     :samp:`armv8.5-a`, :samp:`+bf16`, :samp:`+i8mm`
:samp:`armv8-r`       Armv8-R       :samp:`armv8-r`
====================  ============  =====================================================================

```
